"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)7ii6l91vxlad--ak$a2ous-&!mb_*magje06mq)^&q##3m8pe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'ezygrocery',  
]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Update these to match your actual app name
                'ezygrocery.context_processors.store_settings',
                'ezygrocery.context_processors.cart_items',
                'ezygrocery.context_processors.categories_processor',
                'ezygrocery.context_processors.trending_searches',
                'ezygrocery.context_processors.promotions_processor',
                'ezygrocery.context_processors.special_offers_processor',
                'ezygrocery.context_processors.coupons_processor',
                'ezygrocery.context_processors.get_new_orders_badge',          
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'bn-bd'  # Bangla
TIME_ZONE = 'Asia/Dhaka'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== EMAIL SETTINGS ====================
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development

# ==================== SESSION SETTINGS ====================
SESSION_COOKIE_AGE = 86400 * 30  # 30 days
SESSION_SAVE_EVERY_REQUEST = True

# ==================== SECURITY SETTINGS (Production) ====================
if not DEBUG:
    # HTTPS Settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS Settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ==================== LOGGING ====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'ezygrocery': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if not exists
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir()
# ==================== UNFOLD ADMIN CONFIGURATION ====================
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def admin_changelist(app_label, model_name):
    """Helper function to generate admin changelist URL"""
    return lambda request: reverse_lazy(f"admin:{app_label}_{model_name}_changelist")
UNFOLD = {
    "SITE_TITLE": "কাছের দোকান Admin Panel",
    "SITE_HEADER": "কাছের দোকান Administration",
    "SITE_URL": "/",
    "SITE_SYMBOL": "speed",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "config.settings.environment_callback",
    
    "COLORS": {
        "primary": {
            "50": "239 249 254",   # Very light blue
            "100": "220 242 251",  # Light blue
            "200": "186 230 248",  # Lighter blue
            "300": "135 206 235",  # Sky blue
            "400": "58 144 196",   # Medium blue
            "500": "26 77 109",    # Main dark blue (#1a4d6d)
            "600": "21 62 87",     # Darker blue
            "700": "16 47 66",     # Very dark blue
            "800": "13 45 69",     # Darkest blue
            "900": "10 36 55",     # Almost black blue
            "950": "8 29 44",      # Deep blue-black
        },
        "font": {
            "subtle-light": "148 163 184",
            "default-light": "30 41 59",
            "subtle-dark": "148 163 184",
            "default-dark": "226 232 240",
        },
    },
    
    "STYLES": [
        lambda request: static("admin/css/custom_sidebar.css"),
        lambda request: static("admin/css/custom_tabs.css"),
    ],
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            # ==================== DASHBOARD ====================
            {
                "title": _("📊 ড্যাশবোর্ড"),
                "separator": True,
                "items": [
                    {
                        "title": _("ড্যাশবোর্ড"),
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                    {
                        "title": _("সাইট দেখুন"),
                        "icon": "visibility",
                        "link": "/",
                    },
                ],
            },
            
            # ==================== LOCATIONS & SHOPS ====================
            {
                "title": _("📍 স্থান ও দোকান"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("মহল্লা সমূহ"),
                        "icon": "location_on",
                        "link": admin_changelist("ezygrocery", "moholla"),
                    },
                    {
                        "title": _("দোকান সমূহ"),
                        "icon": "store",
                        "link": admin_changelist("ezygrocery", "shop"),
                    },
                ],
            },
            
            # ==================== PRODUCT MANAGEMENT ====================
            {
                "title": _("📦 পণ্য ব্যবস্থাপনা"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("ক্যাটাগরি সমূহ"),
                        "icon": "category",
                        "link": admin_changelist("ezygrocery", "category"),
                    },
                    {
                        "title": _("মূল পণ্য সমূহ"),
                        "icon": "inventory_2",
                        "link": admin_changelist("ezygrocery", "masterproduct"),
                    },
                    {
                        "title": _("দোকানের পণ্য সমূহ"),
                        "icon": "storefront",
                        "link": admin_changelist("ezygrocery", "shopproduct"),
                    },
                    {
                        "title": _("পণ্য রিভিউ"),
                        "icon": "star_rate",
                        "link": admin_changelist("ezygrocery", "masterproductreview"),
                    },
                ],
            },
            
            # ==================== ORDER MANAGEMENT ====================
            {
                "title": _("🛒 অর্ডার ব্যবস্থাপনা"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("অর্ডার সমূহ"),
                        "icon": "receipt_long",
                        "link": admin_changelist("ezygrocery", "order"),
                    },
                    {
                        "title": _("অর্ডার আইটেম"),
                        "icon": "list_alt",
                        "link": admin_changelist("ezygrocery", "orderitem"),
                    },
                    {
                        "title": _("রিফান্ড রিকোয়েস্ট"),
                        "icon": "currency_exchange",
                        "link": admin_changelist("ezygrocery", "refundrequest"),
                    },
                    {
                        "title": _("কার্ট সমূহ"),
                        "icon": "shopping_cart",
                        "link": admin_changelist("ezygrocery", "cart"),
                    },
                    {
                        "title": _("কার্ট আইটেম"),
                        "icon": "shopping_basket",
                        "link": admin_changelist("ezygrocery", "cartitem"),
                    },
                ],
            },
            
            # ==================== CUSTOMERS & USERS ====================
            {
                "title": _("👥 গ্রাহক ও ব্যবহারকারী"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("ব্যবহারকারী"),
                        "icon": "people",
                        "link": lambda request: reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("গ্রুপ"),
                        "icon": "group",
                        "link": lambda request: reverse_lazy("admin:auth_group_changelist"),
                    },
                    {
                        "title": _("গ্রাহক প্রোফাইল"),
                        "icon": "person",
                        "link": admin_changelist("ezygrocery", "customer"),
                    },
                ],
            },
            
            # ==================== DELIVERY & RIDERS ====================
            {
                "title": _("🚴 ডেলিভারি ব্যবস্থাপনা"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("রাইডার সমূহ"),
                        "icon": "delivery_dining",
                        "link": admin_changelist("ezygrocery", "rider"),
                    },
                    {
                        "title": _("রাইডার আর্নিং"),
                        "icon": "payments",
                        "link": admin_changelist("ezygrocery", "riderearning"),
                    },
                    {
                        "title": _("ক্যাশ ডিপোজিট"),
                        "icon": "account_balance_wallet",
                        "link": admin_changelist("ezygrocery", "ridercashdeposit"),
                    },
                    {
                        "title": _("ডেলিভারি জোন"),
                        "icon": "map",
                        "link": admin_changelist("ezygrocery", "deliveryzone"),
                    },
                    {
                        "title": _("দূরত্ব স্ল্যাব"),
                        "icon": "straighten",
                        "link": admin_changelist("ezygrocery", "distanceslab"),
                    },
                    {
                        "title": _("সার্জ পলিসি"),
                        "icon": "trending_up",
                        "link": admin_changelist("ezygrocery", "surgepolicy"),
                    },
                ],
            },
            
            # ==================== MARKETING & PROMOTIONS ====================
            {
                "title": _("🎯 মার্কেটিং ও প্রমোশন"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("কুপন সমূহ"),
                        "icon": "local_offer",
                        "link": admin_changelist("ezygrocery", "coupon"),
                    },
                    {
                        "title": _("প্রমোশন সমূহ"),
                        "icon": "campaign",
                        "link": admin_changelist("ezygrocery", "promotion"),
                    },
                    {
                        "title": _("বিশেষ অফার"),
                        "icon": "star",
                        "link": admin_changelist("ezygrocery", "specialoffer"),
                    },
                    {
                        "title": _("হিরো স্লাইডার"),
                        "icon": "view_carousel",
                        "link": admin_changelist("ezygrocery", "heroslider"),
                    },
                ],
            },
            
            # ==================== CONTENT & SEO ====================
            {
                "title": _("📝 কন্টেন্ট ও SEO"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("ব্লগ পোস্ট"),
                        "icon": "article",
                        "link": admin_changelist("ezygrocery", "blogpost"),
                    },
                    {
                        "title": _("FAQ সমূহ"),
                        "icon": "help_outline",
                        "link": admin_changelist("ezygrocery", "faq"),
                    },
                    {
                        "title": _("যোগাযোগ বার্তা"),
                        "icon": "contact_mail",
                        "link": admin_changelist("ezygrocery", "contactmessage"),
                    },
                    {
                        "title": _("সার্চ কোয়েরি"),
                        "icon": "search",
                        "link": admin_changelist("ezygrocery", "searchquery"),
                    },
                ],
            },
            
            # ==================== REPORTS & ANALYTICS ====================
            {
                "title": _("📊 রিপোর্ট ও বিশ্লেষণ"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("দোকান বিক্রয় রিপোর্ট"),
                        "icon": "assessment",
                        "link": admin_changelist("ezygrocery", "shopsalesreport"),
                    },
                ],
            },
            
            # ==================== SETTINGS & CONFIGURATION ====================
            {
                "title": _("⚙️ সেটিংস ও কনফিগারেশন"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("স্টোর সেটিংস"),
                        "icon": "settings",
                        "link": admin_changelist("ezygrocery", "storesettings"),
                    },
                    {
                        "title": _("সাইটম্যাপ কনফিগ"),
                        "icon": "public",
                        "link": admin_changelist("ezygrocery", "sitemapconfig"),
                    },
                ],
            },
        ],
    },
}