# Generated by Django 5.2.6 on 2025-11-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezygrocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='product_image_url',
            field=models.URLField(blank=True, help_text='If no image uploaded, use this URL', verbose_name='পণ্যের ছবি URL'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='product_image_url',
            field=models.URLField(blank=True, help_text='Override product image with this URL', verbose_name='পণ্যের ছবি URL'),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='master_products/', verbose_name='মূল ছবি'),
        ),
    ]
